package mil.navair.iframework.common.reportUtils;

import java.io.Serializable;

/**
 * This is a definition of the types of messages that an application 
 * creates and may like to propagate through the framework. 
 */
public class MessageType implements Serializable {

    private Integer identifier; //this value would be generated by the framework upon provisioning
    private String name; //name used to identify a message type
    private String description;
    private String schemaURL; //in the case of an XML document, this is the URL to the XSD that defines the message
    private String className; //in the case of a Java object, this is the fully qualified class name

    /**
     * Get the identifier of this message type.
     * @return message type id
     */
    public Integer getIdentifier() {
        return identifier;
    }

    /**
     * Set the id for this message type.
     * This is set by the framework and should not be modified
     * by anything else.
     * @param identifier new id 
     */
    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    /**
     * Get the name of this message type
     * @return message type name
     */
    public String getName() {
        return name;
    }

    /**
     * Set the name of this message type
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the description of this message type
     * @return description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set the description of this message type
     * @param description new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * In the case of an XML document, this is the URL to 
     * the XSD that defines the message
     * @return schema url
     */
    public String getSchemaURL() {
        return schemaURL;
    }

    /**
     * Set the URL to the XSD that defines this message type.
     * @param schemaURL new URL
     */
    public void setSchemaURL(String schemaURL) {
        this.schemaURL = schemaURL;
    }

    /**
     * In the case of a Java object, this is the fully qualified class name
     * @return Java Class Name
     */
    public String getClassName() {
        return className;
    }

    /**
     * Set the Class Name of the Java Object that this message type
     * represents.
     * @param className Java Class Name
     */
    public void setClassName(String className) {
        this.className = className;
    }

    @Override
    public String toString() {
        return "MessageType ["
                + "\n\tidentifier => " + identifier
                + "\n\tname => " + name
                + "\n\tdescription => " + description
                + "\n\tschemaURL => " + schemaURL
                + "\n\tclassName => " + className + ']';
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MessageType other = (MessageType) obj;
        if (this.identifier != other.identifier && (this.identifier == null || !this.identifier.equals(other.identifier))) {
            return false;
        }
        if ((this.name == null) ? (other.name != null) : !this.name.equals(other.name)) {
            return false;
        }
        if ((this.description == null) ? (other.description != null) : !this.description.equals(other.description)) {
            return false;
        }
        if ((this.schemaURL == null) ? (other.schemaURL != null) : !this.schemaURL.equals(other.schemaURL)) {
            return false;
        }
        if ((this.className == null) ? (other.className != null) : !this.className.equals(other.className)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + (this.identifier != null ? this.identifier.hashCode() : 0);
        hash = 53 * hash + (this.name != null ? this.name.hashCode() : 0);
        hash = 53 * hash + (this.description != null ? this.description.hashCode() : 0);
        hash = 53 * hash + (this.schemaURL != null ? this.schemaURL.hashCode() : 0);
        hash = 53 * hash + (this.className != null ? this.className.hashCode() : 0);
        return hash;
    }

    
}
